version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing Node.js dependencies...
      - node --version
      - npm --version
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - echo Building the React app with Vite...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Build output directory contents:
      - ls -la dist/ || echo "dist directory not found"
      - echo Checking if build was successful...
      - test -d dist && echo "Build successful - dist directory exists" || (echo "Build failed - dist directory not found" && exit 1)

artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: frontend-build-$(date +%Y-%m-%d)

cache:
  paths:
    - 'node_modules/**/*'

